[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false
maxMessageSize = 50

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[client]
showErrorDetails = true